import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
import {INITIAL_BUILDING_DATA as data} from '../data/buildingGraph.js';
import {INDOOR_ROUTE_NETWORKS} from '../data/indoorRouteNetworks.js';
import {findSafestEvacuationPath,findShortestPath} from '../utils/pathfinder.js';
const html=fs.readFileSync(new URL('../mobile.html',import.meta.url),'utf8');
const ctx={window:{SafeWay:{INDOOR_ROUTE_NETWORKS}},SafeWay:{INDOOR_ROUTE_NETWORKS}};vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf('    function campusDistanceEdges'),html.indexOf('    let audioCtx'))+'\nthis.api={campusDistanceEdges,buildMultiFloorStagePipeline,BLOCK_STAIRS_OPTIONS,getControlId};',ctx);
const edges=ctx.api.campusDistanceEdges(data.nodes,data.edges);
const options={isEmergency:true,accessibilityMode:false};
const run=(es=edges,exits=data.exits,opts=options)=>findSafestEvacuationPath('admin',data.nodes,es,exits,data.assemblyAreas,opts,{},{});
const normalEmergency=run();assert(normalEmergency.bestRoute);
assert(normalEmergency.bestRoute.pathNodes.at(-1).type==='assembly');
const blockedEdge=normalEmergency.bestRoute.edges[0].id;
const blocked=run(edges.map(e=>e.id===blockedEdge?{...e,blocked:true}:e));
assert(!blocked.bestRoute?.edges.some(e=>e.id===blockedEdge));
const burning=run(edges.map(e=>e.id===blockedEdge?{...e,hazardLevel:'high'}:e));
assert(!burning.bestRoute?.edges.some(e=>e.id===blockedEdge));
const accessible=run(edges,data.exits,{...options,accessibilityMode:true});
assert(!accessible.bestRoute?.edges.some(e=>!e.stepFree));
const closedId=normalEmergency.bestRoute.pathNodes.find(n=>n.type==='exit')?.id;
const closed=run(edges,data.exits.map(e=>e.id===closedId?{...e,isOpen:false}:e));
assert(!closed.bestRoute?.pathNodeIds.includes(closedId));
const args={activeOriginLocation:{mapId:'ramanujan-first',name:'Drawing Lab',point:[500,235]},activeDestLocation:{mapId:'kalpana-first',name:'Training Hall',point:[300,325]},activeCampusRoute:normalEmergency.bestRoute,liveState:{emergencyActive:true},bData:data,accessibilityMode:false};
const stages=ctx.api.buildMultiFloorStagePipeline(args);
assert.equal(stages.at(-1).mapId,'campus');
assert.equal(stages.at(-1).targetLabel,normalEmergency.bestRoute.pathNodes.at(-1).name);
assert(!stages.some(s=>s.mapId==='kalpana-first'));
const unavailable=ctx.api.buildMultiFloorStagePipeline({...args,activeCampusRoute:null});
assert.equal(unavailable[0].d,'');assert.equal(unavailable[0].stageKey,'no-safe-route');
// A blocked preferred stair may not be chosen when a viable alternative exists.
const stair=ctx.api.BLOCK_STAIRS_OPTIONS['ramanujan-first'][0];
const stairKey=ctx.api.getControlId('door','ramanujan-first',stair.name);
const alternate=ctx.api.buildMultiFloorStagePipeline({...args,liveState:{emergencyActive:true,blockedEdges:{[stairKey]:true}}});
assert.notEqual(alternate[0].targetLabel,stair.label);
console.log('PASS: corrected emergency geometry, blocked edge, fire, closed exit, step-free, safe destination, no-route state, and alternate stairs.');
